spring: 
  application: 
    name: ribbon-consumer
    
server: 
  port: 8521
  
eureka: 
  client: 
    serviceUrl: 
      #defaultZone: http://william:123456@localhost:1314/eureka/
      defaultZone: http://localhost:1314/eureka/