server:
  port: 52099

##配置服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1314/eureka/

spring:
  rabbitmq: 
     host: localhost
     port: 5672
     username: guest
     password: guest
  application:
    name: config-server
  cloud:
    config:
      ##discovery: 
       ##enabled: true
      #uri: http://localhost:{server.port}
      server:
        git:
          ## uri 配置git仓库位置 
          uri: https://github.com/williamjava/spring_cloud_practise.git
          ## searchPaths 配置仓库路径下的相对搜索位置，可以配置多个 
          searchPaths: config-repository
          ## username 访问git仓库的用户名
          username: wuhoujian@126.com
          ## password 访问git仓库的用户密码 
          password: william&&0914

##自动刷新配置：http://localhost:52099/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh