###通过spring.application.name属性，我们可以指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
###eureka.client.serviceUrl.defaultZone属性对应服务注册中心的配置内容，指定服务注册中心的位置

spring: 
  application: 
    name: feign-consumer
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

server: 
  port: 8888


eureka: 
  client: 
    serviceUrl: 
      ##defaultZone: http://william:123456@peer1:1314/eureka/,http://william:123456@peer2:1315/eureka/
      #defaultZone: http://william:123456@localhost:1314/eureka/
      defaultZone: http://localhost:1314/eureka/

logging: 
  level: 
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG