spring: 
  application: 
    name: star-eureka-server
    
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: william                  # 配置登录的账号是user
    password: 123456       # 配置登录的密码是password123
server:
  port: 1314                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1314/eureka/